#!/usr/bin/env ruby
# frozen_string_literal: true

# A checkout needs lib on the load path; an installed gem already has it there.
lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'slipway'

exit Slipway.run(ARGV)
